
env: development
port: 8443
database_url: "postgres://user:pass@auth-postgres:5432/authdb?sslmode=disable"

redis_url: "redis://redis:6379"
kafka_brokers: "kafka:9092"
aadhaar_api_key: ""

logger:
  level: debug
  encoding: console
  output: stdout
  add_source: false
  time_format: ""

tls:
  hsts_max_age: 63072000
  include_subdomains: true
  preload: true
  csp: "default-src 'self'; frame-ancestors 'none';"
  excluded_paths:
    - /health
    - /ready
    - /live
    - /otp/send
    - /otp/verify
  force_redirect: false
  trust_proxy_header: true

kms:
  key_id: "local"
  local_secret: "super-secret-dev-key-change-me"

  timeout_ms: 10000
  public_key_cache_ttl_ms: 86400000
  encryption_context:
    service: "auth"
    env: "development"

otp:
  code_length: 6
  expiration: 10m
  max_attempts: 3
  resend_cooldown: 30s
  max_daily_per_user: 5
  block_duration: 24h
  require_phone_hash: true
  phone_hash_secret: "dev-secret-change-me"
  delivery_simulation: true
  india_specific_limits: true

india_otp_rate_limit:
  max_per_day: 5
  max_per_hour: 3
  max_per_minute: 1
  block_duration: 24h
  whitelisted_ips:
    - "10.0.0.0/8"
    - "192.168.0.0/16"
  strict_on_failure: true

fingerprint:
  trusted_proxy_ip_headers:
    - "X-Forwarded-For"
    - "X-Real-IP"
  trusted_proxy_cidrs:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  enable_ip_bucketing: true
  privacy_enhanced: false
  server_pepper: "this-is-a-local-pepper-123"
  context_deadline: 100ms
  ua_cache_ttl: 5m



# Certificate rotation policy
certificate_policy:
  rotation_days: 90
  early_rotation_threshold: 15
  key_size: 4096
  signature_algorithm: "SHA256"
  san:
    - "authservice.example.com"
    - "*.authservice.example.com"
  key_usage:
    - "digitalSignature"
    - "keyEncipherment"
  extended_key_usage:
    - "serverAuth"
  backup_count: 5
  encryption:
    kms_key: "local"
  monitoring:
    expiry_param: "/authservice/cert_expiry"
    alert_days: [60, 30, 15, 7, 3, 1]

  telemetry:
  device_audit:
    enabled: false
    endpoint: "https://localhost:9200"
    api_key: ""
    username: ""
    password: ""
    index_prefix: "device-audit"
    flush_size: 500
    flush_every: 2s
    timeout: 5s
  otp_audit:
    enabled: false
    endpoint: "https://localhost:9200"
    api_key: ""
    username: ""
    password: ""
    index_prefix: "otp-audit"
    flush_size: 500
    flush_every: 2s
    timeout: 5s
  kafka:
    enabled: true
    brokers: ["kafka:9092"]
    topic_device: "device_audit"
    topic_otp: "otp_audit"
    batch_size: 500
    flush_every: 2s
    queue_capacity: 2000
    dial_timeout: 5s
    write_timeout: 5s
    tls: false
    sasl_plain: false
    username: ""
    password: ""
  es_sink:
    enabled: true
    endpoint: "http://elasticsearch:9200"
    api_key: ""
    username: ""
    password: ""
    index_prefix: "auth-audit"
    flush_size: 500
    flush_every: 2s
    timeout: 5s
    group_id: "audit-sink-es"
    min_bytes: 10000
    max_bytes: 10000000
    max_wait: 1s
