env: development
port: 8080

database_url: "postgres://user:pass@localhost:5432/authdb?sslmode=disable"
redis_url: "redis://localhost:6379"  # For non-Docker runs; Docker will override via env
kafka_brokers: "localhost:9092"
aadhaar_api_key: ""

logger:
  level: debug
  encoding: console
  output: stdout

tls:
  hsts_max_age: 63072000
  include_subdomains: true
  preload: true
  csp: "default-src 'self'; frame-ancestors 'none';"
  excluded_paths:
    - /health
    - /ready
    - /live
    - /otp/send
    - /otp/verify
  force_redirect: false
  trust_proxy_header: true

kms:
  key_id: ""
  timeout_ms: 10000
  public_key_cache_ttl_ms: 86400000
  encryption_context:
    service: "auth"
    env: "development"

otp:
  code_length: 6
  expiration: 10m
  max_attempts: 3
  resend_cooldown: 30s
  max_daily_per_user: 5
  block_duration: 24h
  require_phone_hash: true
  phone_hash_secret: ""          # overridden by env PHONE_HASH_SECRET in Docker
  delivery_simulation: true
  india_specific_limits: true

india_otp_rate_limit:
  max_per_day: 5
  max_per_hour: 3
  max_per_minute: 1
  block_duration: 24h
  whitelisted_ips:
    - "10.0.0.0/8"
    - "192.168.0.0/16"
  strict_on_failure: true
